# SQLite version 3.x
#   gem install sqlite3-ruby
# sqlite3_example:
development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql
  database: planetashop_production
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password:
  host: localhost
  encoding: utf8

